import { AppLanguage } from '@/constants/appContent';

export const copy = {
  en: {
    brand: 'Aashayein',
    tagline: 'Healthcare bridging for ASHA workers and rural communities',
    splashSubtitle: 'Trusted care, closer to home',
    welcomeEyebrow: 'Community Health Platform',
    welcomeTitle: 'Care that reaches every household',
    welcomeBody:
      'Aashayein helps ASHA workers, rural families and health supervisors stay connected — even with weak network.',
    whyTitle: 'Built for the field',
    getStarted: 'Get Started',
    haveAccount: 'I already have an account',
    languageEyebrow: 'Regional Language',
    languageTitle: 'Choose your language',
    languageBody: 'Hindi and English first. More Indian languages can be added later without redesigning this screen.',
    continue: 'Continue',
    loginEyebrow: 'Secure Sign In',
    loginTitle: 'Welcome back',
    loginBody: 'Use your mobile number or email. Demo accounts below fill the form for the hackathon.',
    mobileOrEmail: 'Mobile or Email',
    mobilePlaceholder: '10-digit mobile or email',
    password: 'Password',
    passwordPlaceholder: 'Enter your password',
    forgotPassword: 'Forgot password?',
    signIn: 'Sign In',
    signInWithOtp: 'Sign in with OTP',
    noAccount: "Don't have an account?",
    register: 'Register',
    demoHint: 'Tap a demo role to fill credentials',
    registerEyebrow: 'Create Account',
    registerTitle: 'Join Aashayein',
    registerBody: 'ASHA workers and rural citizens can self-register. Admin access is assigned separately.',
    fullName: 'Full Name',
    fullNamePlaceholder: 'Enter your full name',
    mobile: 'Mobile Number',
    mobilePlaceholderShort: '10-digit mobile number',
    emailOptional: 'Email (optional)',
    emailPlaceholder: 'Enter email address',
    village: 'Village',
    villagePlaceholder: 'Your village',
    district: 'District',
    districtPlaceholder: 'Your district',
    confirmPassword: 'Confirm Password',
    confirmPasswordPlaceholder: 'Re-enter your password',
    continueOtp: 'Continue to OTP',
    hasAccount: 'Already have an account?',
    signInLink: 'Sign In',
    otpEyebrow: 'Verify Identity',
    otpTitle: 'Enter verification code',
    otpBody: 'We sent a 6-digit code to',
    otpBodyFallback: 'Enter the OTP sent to your mobile number',
    verifyContinue: 'Verify & Continue',
    resetPassword: 'Reset Password',
    resendOtp: 'Resend OTP',
    resendIn: 'Resend in',
    sending: 'Sending...',
    backToSignIn: 'Back to Sign In',
    newPassword: 'New Password',
    newPasswordPlaceholder: 'Enter new password',
    confirmNewPassword: 'Confirm New Password',
    forgotEyebrow: 'Account Recovery',
    forgotTitle: 'Forgot password',
    forgotBody: 'Enter the mobile number registered with Aashayein. We will send a reset OTP.',
    sendResetOtp: 'Send Reset OTP',
    roleLabel: 'Who are you?',
    otpLabel: '6-digit OTP',
    demoOtp: 'Demo OTP: 123456',
  },
  hi: {
    brand: 'आशाएँ',
    tagline: 'आशा कार्यकर्ताओं और ग्रामीण समुदायों के लिए स्वास्थ्य सेतु',
    splashSubtitle: 'भरोसेमंद देखभाल, आपके घर के पास',
    welcomeEyebrow: 'सामुदायिक स्वास्थ्य मंच',
    welcomeTitle: 'हर घर तक पहुँचने वाली देखभाल',
    welcomeBody:
      'आशाएँ आशा कार्यकर्ताओं, ग्रामीण परिवारों और स्वास्थ्य पर्यवेक्षकों को जोड़ती है — कमज़ोर नेटवर्क में भी।',
    whyTitle: 'मैदान के लिए बना',
    getStarted: 'शुरू करें',
    haveAccount: 'मेरा खाता पहले से है',
    languageEyebrow: 'क्षेत्रीय भाषा',
    languageTitle: 'अपनी भाषा चुनें',
    languageBody: 'पहले हिन्दी और अंग्रेज़ी। बाद में और भारतीय भाषाएँ बिना स्क्रीन बदले जोड़ सकते हैं।',
    continue: 'आगे बढ़ें',
    loginEyebrow: 'सुरक्षित प्रवेश',
    loginTitle: 'वापसी पर स्वागत है',
    loginBody: 'मोबाइल नंबर या ईमेल से प्रवेश करें। डेमो खाते फ़ॉर्म भर देते हैं।',
    mobileOrEmail: 'मोबाइल या ईमेल',
    mobilePlaceholder: '10 अंकों का मोबाइल या ईमेल',
    password: 'पासवर्ड',
    passwordPlaceholder: 'अपना पासवर्ड लिखें',
    forgotPassword: 'पासवर्ड भूल गए?',
    signIn: 'प्रवेश करें',
    signInWithOtp: 'OTP से प्रवेश करें',
    noAccount: 'खाता नहीं है?',
    register: 'पंजीकरण',
    demoHint: 'डेमो भूमिका पर टैप करें',
    registerEyebrow: 'खाता बनाएँ',
    registerTitle: 'आशाएँ से जुड़ें',
    registerBody: 'आशा कार्यकर्ता और ग्रामीण नागरिक स्वयं पंजीकरण कर सकते हैं।',
    fullName: 'पूरा नाम',
    fullNamePlaceholder: 'अपना पूरा नाम लिखें',
    mobile: 'मोबाइल नंबर',
    mobilePlaceholderShort: '10 अंकों का मोबाइल',
    emailOptional: 'ईमेल (वैकल्पिक)',
    emailPlaceholder: 'ईमेल पता',
    village: 'गाँव',
    villagePlaceholder: 'आपका गाँव',
    district: 'ज़िला',
    districtPlaceholder: 'आपका ज़िला',
    confirmPassword: 'पासवर्ड पुष्टि',
    confirmPasswordPlaceholder: 'पासवर्ड फिर लिखें',
    continueOtp: 'OTP पर जाएँ',
    hasAccount: 'पहले से खाता है?',
    signInLink: 'प्रवेश करें',
    otpEyebrow: 'पहचान सत्यापित करें',
    otpTitle: 'सत्यापन कोड लिखें',
    otpBody: 'हमने 6 अंकों का कोड भेजा है',
    otpBodyFallback: 'अपने मोबाइल पर आया OTP लिखें',
    verifyContinue: 'सत्यापित करें',
    resetPassword: 'पासवर्ड रीसेट',
    resendOtp: 'OTP फिर भेजें',
    resendIn: 'फिर भेजें',
    sending: 'भेजा जा रहा है...',
    backToSignIn: 'प्रवेश पर वापस',
    newPassword: 'नया पासवर्ड',
    newPasswordPlaceholder: 'नया पासवर्ड',
    confirmNewPassword: 'नया पासवर्ड पुष्टि',
    forgotEyebrow: 'खाता पुनर्प्राप्ति',
    forgotTitle: 'पासवर्ड भूल गए',
    forgotBody: 'आशाएँ पर पंजीकृत मोबाइल नंबर लिखें। हम रीसेट OTP भेजेंगे।',
    sendResetOtp: 'रीसेट OTP भेजें',
    roleLabel: 'आप कौन हैं?',
    otpLabel: '6 अंकों का OTP',
    demoOtp: 'डेमो OTP: 123456',
  },
  pa: {
    brand: 'ਆਸ਼ਾਏਂ',
    tagline: 'ਆਸ਼ਾ ਵਰਕਰਾਂ ਅਤੇ ਪੇਂਡੂ ਭਾਈਚਾਰਿਆਂ ਲਈ ਸਿਹਤ ਸੇਤੂ',
    splashSubtitle: 'ਭਰੋਸੇਯੋਗ ਦੇਖਭਾਲ, ਘਰ ਦੇ ਨੇੜੇ',
    welcomeEyebrow: 'ਕਮਿਊਨਿਟੀ ਹੈਲਥ ਪਲੇਟਫਾਰਮ',
    welcomeTitle: 'ਹਰ ਘਰ ਤੱਕ ਪਹੁੰਚਣ ਵਾਲੀ ਦੇਖਭਾਲ',
    welcomeBody:
      'ਆਸ਼ਾਏਂ ਆਸ਼ਾ ਵਰਕਰਾਂ, ਪੇਂਡੂ ਪਰਿਵਾਰਾਂ ਅਤੇ ਸਿਹਤ ਸੁਪਰਵਾਈਜ਼ਰਾਂ ਨੂੰ ਜੋੜਦਾ ਹੈ — ਕਮਜ਼ੋਰ ਨੈੱਟਵਰਕ ਵਿੱਚ ਵੀ।',
    whyTitle: 'ਖੇਤਰ ਲਈ ਬਣਾਇਆ',
    getStarted: 'ਸ਼ੁਰੂ ਕਰੋ',
    haveAccount: 'ਮੇਰਾ ਖਾਤਾ ਪਹਿਲਾਂ ਹੀ ਹੈ',
    languageEyebrow: 'ਖੇਤਰੀ ਭਾਸ਼ਾ',
    languageTitle: 'ਆਪਣੀ ਭਾਸ਼ਾ ਚੁਣੋ',
    languageBody: 'ਪਹਿਲਾਂ ਹਿੰਦੀ ਅਤੇ ਅੰਗਰੇਜ਼ੀ। ਬਾਅਦ ਵਿੱਚ ਹੋਰ ਭਾਰਤੀ ਭਾਸ਼ਾਵਾਂ ਜੋੜੀਆਂ ਜਾ ਸਕਦੀਆਂ ਹਨ।',
    continue: 'ਅੱਗੇ ਵਧੋ',
    loginEyebrow: 'ਸੁਰੱਖਿਅਤ ਸਾਈਨ ਇਨ',
    loginTitle: 'ਵਾਪਸੀ ਤੇ ਸੁਆਗਤ',
    loginBody: 'ਮੋਬਾਈਲ ਜਾਂ ਈਮੇਲ ਨਾਲ ਸਾਈਨ ਇਨ ਕਰੋ। ਡੈਮੋ ਖਾਤੇ ਫਾਰਮ ਭਰ ਦਿੰਦੇ ਹਨ।',
    mobileOrEmail: 'ਮੋਬਾਈਲ ਜਾਂ ਈਮੇਲ',
    mobilePlaceholder: '10 ਅੰਕਾਂ ਦਾ ਮੋਬਾਈਲ ਜਾਂ ਈਮੇਲ',
    password: 'ਪਾਸਵਰਡ',
    passwordPlaceholder: 'ਆਪਣਾ ਪਾਸਵਰਡ ਲਿਖੋ',
    forgotPassword: 'ਪਾਸਵਰਡ ਭੁੱਲ ਗਏ?',
    signIn: 'ਸਾਈਨ ਇਨ',
    signInWithOtp: 'OTP ਨਾਲ ਸਾਈਨ ਇਨ',
    noAccount: 'ਖਾਤਾ ਨਹੀਂ ਹੈ?',
    register: 'ਰਜਿਸਟਰ',
    demoHint: 'ਡੈਮੋ ਰੋਲ ਤੇ ਟੈਪ ਕਰੋ',
    registerEyebrow: 'ਖਾਤਾ ਬਣਾਓ',
    registerTitle: 'ਆਸ਼ਾਏਂ ਨਾਲ ਜੁੜੋ',
    registerBody: 'ਆਸ਼ਾ ਵਰਕਰ ਅਤੇ ਪੇਂਡੂ ਨਾਗਰਿਕ ਖੁਦ ਰਜਿਸਟਰ ਕਰ ਸਕਦੇ ਹਨ।',
    fullName: 'ਪੂਰਾ ਨਾਮ',
    fullNamePlaceholder: 'ਆਪਣਾ ਪੂਰਾ ਨਾਮ',
    mobile: 'ਮੋਬਾਈਲ ਨੰਬਰ',
    mobilePlaceholderShort: '10 ਅੰਕਾਂ ਦਾ ਮੋਬਾਈਲ',
    emailOptional: 'ਈਮੇਲ (ਵਿਕਲਪਿਕ)',
    emailPlaceholder: 'ਈਮੇਲ ਪਤਾ',
    village: 'ਪਿੰਡ',
    villagePlaceholder: 'ਤੁਹਾਡਾ ਪਿੰਡ',
    district: 'ਜ਼ਿਲ੍ਹਾ',
    districtPlaceholder: 'ਤੁਹਾਡਾ ਜ਼ਿਲ੍ਹਾ',
    confirmPassword: 'ਪਾਸਵਰਡ ਪੁਸ਼ਟੀ',
    confirmPasswordPlaceholder: 'ਪਾਸਵਰਡ ਦੁਬਾਰਾ ਲਿਖੋ',
    continueOtp: 'OTP ਤੇ ਜਾਓ',
    hasAccount: 'ਪਹਿਲਾਂ ਤੋਂ ਖਾਤਾ ਹੈ?',
    signInLink: 'ਸਾਈਨ ਇਨ',
    otpEyebrow: 'ਪਛਾਣ ਤਸਦੀਕ',
    otpTitle: 'ਤਸਦੀਕ ਕੋਡ ਲਿਖੋ',
    otpBody: 'ਅਸੀਂ 6 ਅੰਕਾਂ ਦਾ ਕੋਡ ਭੇਜਿਆ ਹੈ',
    otpBodyFallback: 'ਮੋਬਾਈਲ ਤੇ ਆਇਆ OTP ਲਿਖੋ',
    verifyContinue: 'ਤਸਦੀਕ ਕਰੋ',
    resetPassword: 'ਪਾਸਵਰਡ ਰੀਸੈੱਟ',
    resendOtp: 'OTP ਮੁੜ ਭੇਜੋ',
    resendIn: 'ਮੁੜ ਭੇਜੋ',
    sending: 'ਭੇਜਿਆ ਜਾ ਰਿਹਾ ਹੈ...',
    backToSignIn: 'ਸਾਈਨ ਇਨ ਤੇ ਵਾਪਸ',
    newPassword: 'ਨਵਾਂ ਪਾਸਵਰਡ',
    newPasswordPlaceholder: 'ਨਵਾਂ ਪਾਸਵਰਡ',
    confirmNewPassword: 'ਨਵਾਂ ਪਾਸਵਰਡ ਪੁਸ਼ਟੀ',
    forgotEyebrow: 'ਖਾਤਾ ਰਿਕਵਰੀ',
    forgotTitle: 'ਪਾਸਵਰਡ ਭੁੱਲ ਗਏ',
    forgotBody: 'ਰਜਿਸਟਰਡ ਮੋਬਾਈਲ ਨੰਬਰ ਲਿਖੋ। ਅਸੀਂ ਰੀਸੈੱਟ OTP ਭੇਜਾਂਗੇ।',
    sendResetOtp: 'ਰੀਸੈੱਟ OTP ਭੇਜੋ',
    roleLabel: 'ਤੁਸੀਂ ਕੌਣ ਹੋ?',
    otpLabel: '6 ਅੰਕਾਂ ਦਾ OTP',
    demoOtp: 'ਡੈਮੋ OTP: 123456',
  },
} as const satisfies Record<AppLanguage, Record<string, string>>;

export type CopyKey = keyof typeof copy.en;
