import { AppButton } from '@/components/ui/AppButton';
import { AppText } from '@/components/ui/AppText';
import { BaseCard } from '@/components/ui/BaseCard';
import { Screen } from '@/components/ui/Screen';
import { useAshaCase, useFacilities, useVisit } from '@/hooks/useAshaQueries';
import { formatDate } from '@/utils/asha';
import { router, useLocalSearchParams } from 'expo-router';
import { ArrowLeft } from 'lucide-react-native';
import { ActivityIndicator, Pressable, View } from 'react-native';
export default function VisitDetailsScreen() { const { id } = useLocalSearchParams<{ id: string }>(); const { data: visit, isLoading: visitLoading, error: visitError } = useVisit(Number(id)); const { data: caseItem, isLoading: caseLoading, error: caseError } = useAshaCase(visit?.caseId); const { data: facilities = [], isLoading: facilitiesLoading, error: facilitiesError } = useFacilities(); const isLoading = visitLoading || caseLoading || facilitiesLoading; const error = visitError ?? caseError ?? facilitiesError; if (isLoading) return <Screen header={<Header title="Visit Details" />}><View className="flex-1 items-center justify-center"><ActivityIndicator color="#0F766E" /><AppText variant="caption" className="mt-3">Loading visit details...</AppText></View></Screen>; if (error) return <Screen header={<Header title="Visit Details" />}><AppText variant="title">Unable to load visit details.</AppText><AppText variant="caption" className="mt-1">Please check your connection and try again.</AppText></Screen>; if (!visit || !caseItem?.patient) return <Screen header={<Header title="Visit Details" />}><AppText variant="title">Visit not found</AppText></Screen>; const patient = caseItem.patient; const facility = visit.facilityId ? facilities.find((item) => item.id === visit.facilityId) : undefined; const referral = caseItem.referrals?.[0]; return <Screen scrollable header={<Header title="Visit Details" />}><BaseCard><AppText variant="title">{caseItem.patientName ?? patient.name}</AppText><AppText variant="caption">{formatDate(visit.visitedAt)} - ASHA worker</AppText><View className="mt-4 gap-3"><AppButton title="View Patient" variant="outline" onPress={() => router.push({ pathname: '/(asha)/patients/[id]', params: { id: String(patient.id) } })} /><AppButton title="View Case" variant="outline" onPress={() => router.push({ pathname: '/(asha)/cases/[id]', params: { id: String(caseItem.id) } })} /></View></BaseCard><AppText variant="title" className="mb-3 mt-2">Observations</AppText><BaseCard><Row label="Temperature" value={visit.temperature ? `${visit.temperature} F` : 'Not recorded'} /><Row label="Condition" value={visit.condition} /><Row label="Symptoms" value={visit.symptoms} /><Row label="Notes" value={visit.notes ?? 'No additional notes'} /></BaseCard><AppText variant="title" className="mb-3 mt-2">Visit Information</AppText><BaseCard><Row label="Visited" value={formatDate(visit.visitedAt)} /><Row label="Facility" value={facility?.name ?? 'Not recorded'} /></BaseCard>{referral ? <><AppText variant="title" className="mb-3 mt-2">Referral</AppText><BaseCard className="border-critical bg-critical-light"><Row label="Status" value={referral.status} /><Row label="Facility" value={referral.facilityName ?? 'Not recorded'} /><Row label="Reason" value={referral.reason} /></BaseCard></> : <AppText variant="caption" className="mt-2">No referral created for this visit.</AppText>}</Screen>; }
function Row({ label, value }: { label: string; value: string }) { return <View className="mb-3"><AppText variant="caption">{label}</AppText><AppText variant="body" className="mt-0.5 text-text-secondary">{value}</AppText></View>; } function Header({ title }: { title: string }) { return <View className="flex-row items-center border-b border-border bg-surface px-4 py-4"><Pressable onPress={() => router.back()} className="mr-3 min-h-touch min-w-touch items-center justify-center"><ArrowLeft size={21} color="#0F172A" /></Pressable><AppText variant="display" className="text-xl">{title}</AppText></View>; }
