import { StatusBadge } from '@/components/asha/StatusBadge';
import { AppButton } from '@/components/ui/AppButton';
import { AppText } from '@/components/ui/AppText';
import { BaseCard } from '@/components/ui/BaseCard';
import { PriorityChip, getPriorityFromScore } from '@/components/ui/PriorityChip';
import { Screen } from '@/components/ui/Screen';
import { useAshaStore } from '@/stores/ashaStore';
import { ageFromDob, formatDate, patientName } from '@/utils/asha';
import { router, useLocalSearchParams } from 'expo-router';
import { ArrowLeft, ChevronRight } from 'lucide-react-native';
import { Pressable, View } from 'react-native';

export default function CaseDetailsScreen() {
  const { id } = useLocalSearchParams<{ id: string }>(); const cases = useAshaStore((state) => state.cases); const patients = useAshaStore((state) => state.patients); const users = useAshaStore((state) => state.patientUsers); const visits = useAshaStore((state) => state.visits);
  const item = cases.find((entry) => entry.id === Number(id)); const patient = patients.find((entry) => entry.id === item?.patientId); const user = users.find((entry) => entry.id === patient?.userId);
  if (!item || !patient) return <Screen><AppText variant="title">Case not found</AppText></Screen>;
  return <Screen scrollable header={<View className="flex-row items-center border-b border-border-subtle bg-surface px-4 py-4"><Pressable onPress={() => router.back()} className="mr-3 min-h-touch min-w-touch items-center justify-center"><ArrowLeft size={21} color="#0F172A" /></Pressable><AppText variant="display" className="text-xl">Case Details</AppText></View>}><BaseCard><View className="flex-row justify-between gap-2"><View><AppText variant="caption">Case #{item.id}</AppText><AppText variant="title" className="mt-1">{patientName(patient, users)}</AppText></View><PriorityChip level={getPriorityFromScore(item.priorityScore)} label={`${getPriorityFromScore(item.priorityScore)} Â· ${item.priorityScore}/10`} /></View><View className="mt-3"><StatusBadge status={item.status} /></View><AppText variant="caption" className="mt-3">Created {formatDate(item.createdAt)} Â· Updated {formatDate(item.updatedAt)}</AppText></BaseCard><Section title="Symptoms"><AppText variant="body">{item.symptoms}</AppText><AppText variant="caption" className="mt-2">Duration: {item.duration}</AppText></Section><Section title="Case Summary"><AppText variant="body" className="text-text-secondary">{item.summary}</AppText></Section><Pressable onPress={() => router.push({ pathname: '/(asha)/patients/[id]', params: { id: String(patient.id) } })}><BaseCard><View className="flex-row items-center justify-between"><View><AppText variant="subtitle" className="text-primary">Patient Information</AppText><AppText variant="label" className="mt-1">{user?.name}</AppText><AppText variant="caption">{ageFromDob(patient.dateOfBirth)} years Â· {patient.gender} Â· {user?.village}, {user?.district}</AppText></View><ChevronRight size={20} color="#94A3B8" /></View></BaseCard></Pressable><AppText variant="title" className="mb-3 mt-2">Visit History</AppText>{visits.filter((visit) => visit.caseId === item.id).map((visit) => <Pressable key={visit.id} onPress={() => router.push({ pathname: '/(asha)/visits/[id]', params: { id: String(visit.id) } })}><BaseCard><View className="flex-row justify-between"><View><AppText variant="label">{formatDate(visit.visitedAt)}</AppText><AppText variant="caption">{visit.condition} Â· {visit.temperature ? `${visit.temperature}Â°F` : 'Temperature not recorded'}</AppText></View><ChevronRight size={20} color="#94A3B8" /></View><AppText variant="caption" className="mt-2">{visit.notes}</AppText></BaseCard></Pressable>)}<View className="mt-2 gap-3"><AppButton title={item.status === 'referred' ? 'View Referral' : 'Add Visit'} onPress={() => item.status === 'referred' ? undefined : router.push({ pathname: '/(asha)/visits/new', params: { caseId: String(item.id) } })} disabled={item.status === 'referred'} /><AppButton title="View Patient" variant="outline" onPress={() => router.push({ pathname: '/(asha)/patients/[id]', params: { id: String(patient.id) } })} /></View></Screen>;
}
function Section({ title, children }: { title: string; children: React.ReactNode }) { return <><AppText variant="title" className="mb-3 mt-2">{title}</AppText><BaseCard>{children}</BaseCard></>; }
