import { AshaBackHeader } from '@/components/asha/AshaBackHeader';
import { SemanticStatusBadge, type SemanticStatusTone } from '@/components/asha/SemanticStatusBadge';
import { AppButton } from '@/components/ui/AppButton';
import { AppText } from '@/components/ui/AppText';
import { BaseCard } from '@/components/ui/BaseCard';
import { Screen } from '@/components/ui/Screen';
import { useAshaStore } from '@/stores/ashaStore';
import type { ReferralStatus } from '@/types/referral';
import { ageFromDob, formatDate, patientName } from '@/utils/asha';
import { router, useLocalSearchParams } from 'expo-router';
import { View } from 'react-native';

const statusPresentation: Record<ReferralStatus, { label: string; tone: SemanticStatusTone }> = { pending: { label: 'Pending', tone: 'warning' }, accepted: { label: 'In progress', tone: 'info' }, completed: { label: 'Completed', tone: 'success' }, declined: { label: 'Declined', tone: 'critical' } };
export default function ReferralDetailsScreen() { const { id } = useLocalSearchParams<{ id: string }>(); const referrals = useAshaStore((state) => state.referrals); const patients = useAshaStore((state) => state.patients); const users = useAshaStore((state) => state.patientUsers); const facilities = useAshaStore((state) => state.facilities); const referral = referrals.find((item) => item.id === Number(id)); const patient = patients.find((item) => item.id === referral?.patientId); const facility = facilities.find((item) => item.id === referral?.facilityId); if (!referral || !patient || !facility) return <Screen header={<AshaBackHeader title="Referral Details" />}><AppText variant="title">Referral not found</AppText></Screen>; const status = statusPresentation[referral.status]; return <Screen scrollable header={<AshaBackHeader title="Referral Details" />}><BaseCard><AppText variant="subtitle" className="text-primary">Patient</AppText><AppText variant="title" className="mt-1">{patientName(patient, users)}</AppText><AppText variant="caption">{ageFromDob(patient.dateOfBirth)} years - {patient.gender}</AppText><AppButton title="View Patient" variant="outline" className="mt-4" onPress={() => router.push({ pathname: '/(asha)/patients/[id]', params: { id: String(patient.id) } })} /></BaseCard><AppText variant="title" className="mb-3 mt-2">Referral Information</AppText><BaseCard><Row label="Reason" value={referral.reason} /><View className="mb-3"><AppText variant="caption">Status</AppText><SemanticStatusBadge label={status.label} tone={status.tone} /></View><Row label="Referred on" value={formatDate(referral.createdAt)} /></BaseCard><AppText variant="title" className="mb-3 mt-2">Healthcare Facility</AppText><BaseCard><Row label="Facility" value={facility.name} /><Row label="Type" value={facility.type} /><Row label="District" value={facility.district} /><Row label="Address" value={facility.address} />{facility.phone ? <Row label="Phone" value={facility.phone} /> : null}</BaseCard></Screen>; }
function Row({ label, value }: { label: string; value: string }) { return <View className="mb-3 last:mb-0"><AppText variant="caption">{label}</AppText><AppText variant="body" className="mt-0.5 text-text-secondary">{value}</AppText></View>; }
