import { AshaBackHeader } from '@/components/asha/AshaBackHeader';
import { EmptyState } from '@/components/asha/EmptyState';
import { SemanticStatusBadge, type SemanticStatusTone } from '@/components/asha/SemanticStatusBadge';
import { AppText } from '@/components/ui/AppText';
import { BaseCard } from '@/components/ui/BaseCard';
import { Screen } from '@/components/ui/Screen';
import { useAshaStore } from '@/stores/ashaStore';
import type { Referral, ReferralStatus } from '@/types/referral';
import { formatDate, patientName } from '@/utils/asha';
import { router, useLocalSearchParams } from 'expo-router';
import { ChevronRight, Search } from 'lucide-react-native';
import { useMemo, useState } from 'react';
import { FlatList, Pressable, TextInput, View } from 'react-native';

const statusPresentation: Record<ReferralStatus, { label: string; tone: SemanticStatusTone }> = { pending: { label: 'Pending', tone: 'warning' }, accepted: { label: 'In progress', tone: 'info' }, completed: { label: 'Completed', tone: 'success' }, declined: { label: 'Declined', tone: 'critical' } };
export default function ReferralsScreen() { const { patientId } = useLocalSearchParams<{ patientId?: string }>(); const referrals = useAshaStore((state) => state.referrals); const patients = useAshaStore((state) => state.patients); const users = useAshaStore((state) => state.patientUsers); const facilities = useAshaStore((state) => state.facilities); const [query, setQuery] = useState(''); const records = useMemo(() => referrals.filter((item) => { const facility = facilities.find((entry) => entry.id === item.facilityId); const matchesPatient = !patientId || item.patientId === Number(patientId); return matchesPatient && `${patientName(patients.find((patient) => patient.id === item.patientId), users)} ${item.reason} ${facility?.name ?? ''}`.toLowerCase().includes(query.toLowerCase()); }), [facilities, patientId, patients, query, referrals, users]); return <Screen header={<AshaBackHeader title="Referrals" subtitle="Track referrals for your assigned patients" />}><View className="mb-3 min-h-touch flex-row items-center rounded-xl border border-border bg-surface-subdued px-3"><Search size={18} color="#94A3B8" /><TextInput value={query} onChangeText={setQuery} placeholder="Search patient, reason or facility" placeholderTextColor="#94A3B8" className="ml-2 flex-1 py-3 text-base text-text-primary" style={{ fontFamily: 'Inter_400Regular' }} /></View><FlatList className="flex-1" data={records} keyExtractor={(item) => String(item.id)} contentContainerClassName="pb-4" ListEmptyComponent={<EmptyState title="No referrals found." message="Try a different search term." />} renderItem={({ item }) => <ReferralCard item={item} patient={patientName(patients.find((entry) => entry.id === item.patientId), users)} facility={facilities.find((entry) => entry.id === item.facilityId)?.name ?? 'Facility not available'} />} /></Screen>; }
function ReferralCard({ item, patient, facility }: { item: Referral; patient: string; facility: string }) { const status = statusPresentation[item.status]; return <Pressable accessibilityRole="button" accessibilityLabel={`Open referral for ${patient}`} onPress={() => router.push({ pathname: '/(asha)/referrals/[id]', params: { id: String(item.id) } })}><BaseCard><View className="flex-row justify-between gap-3"><View className="flex-1"><AppText variant="label">{patient}</AppText><AppText variant="body" className="mt-1 text-text-secondary" numberOfLines={2}>{item.reason}</AppText></View><SemanticStatusBadge label={status.label} tone={status.tone} /></View><AppText variant="caption" className="mt-3">{facility}</AppText><View className="mt-2 flex-row items-center justify-between"><AppText variant="caption">Referred {formatDate(item.createdAt)}</AppText><ChevronRight size={20} color="#94A3B8" /></View></BaseCard></Pressable>; }
